package edu.pw.apsienrollment.common.exception;

public enum ExceptionCode {
    INVALID_CREDENTIALS,
    REFRESH_TOKEN_NOT_VALID,
    REFRESH_TOKEN_NOT_FOUND,
    EVENT_NOT_FOUND,
    UNAUTHORIZED_TO_CREATE_EVENT,
    PLACE_TOO_SMALL,
    PLACE_NOT_AVAILABLE,
    SPEAKER_UNAVAILABLE,
    PLACE_NOT_FOUND,
    VALIDATION_FAILED, USER_NOT_FOUND
}
