package edu.pw.apsienrollment.common.exception;

public enum ExceptionCode {
    INVALID_CREDENTIALS,
    REFRESH_TOKEN_NOT_VALID,
    REFRESH_TOKEN_NOT_FOUND,
    EVENT_NOT_FOUND,
    UNAUTHORIZED_TO_CREATE_EVENT,
    PLACE_TOO_SMALL,
    PLACE_NOT_AVAILABLE,
    SPEAKER_UNAVAILABLE,
    PLACE_NOT_FOUND,
    VALIDATION_FAILED,
    USER_NOT_FOUND,
    USER_ALREADY_SIGNED_UP,
    ATTENDEES_LIMIT_EXCEDED,
    PAYMENT_NOT_FOUND,
    PAYU_EXCEPTION,
    ENROLLMENT_NOT_FOUND,
    QR_CODE_GEN_FAILED,
    ATTENDANCE_NOT_FOUND,
    USER_NOT_AUTHORIZED_TO_CHECK_ATTENDANCE;
}
